### PR TITLE
Moved CONFIG_RTL8821AU variable

### PR DESCRIPTION
**Pull request by konomikitten**
I've moved the CONFIG_RTL8821AU variable to be above where it is referenced. Before this change the CONFIG_RTL8821AU variable was below where it was being referenced causing the build to fail when KERNELRELEASE was defined on the make line.

### CODE REVIEW

**Comment by diederikdehaas** [comment]
Why did you specify KERNELRELEASE on the make line? And what is it for actually? (I don't know)

When I apply your change, then it won't work here ... without KERNELRELEASE ...

**Comment by KonomiKitten** [comment]
Bleh I didn't check to see if it broke the usual build, see: https://www.kernel.org/doc/Documentation/kbuild/modules.txt.

**Comment by diederikdehaas** [comment]
Thanks for the link :+1: 
When you just run `make` (without KERNELRELEASE) it does make an external module, which gets placed in `/lib/modules/$(uname -r)/...` when you later run `sudo make install`.
Is that not what you want?

**Comment by KonomiKitten** [comment]
I tested building with my changes with just the plain old "make" it works fine. This change is needed to satisify the build process as set out by the document I linked from the kernel documentation. This variable is place below where it is referenced which is an error either way and when obj-m is defined the build will fail.

>=== 3. Creating a Kbuild File for an External Module

>In the last section we saw the command to build a module for the
>running kernel. The module is not actually built, however, because a
>build file is required. Contained in this file will be the name of
>the module(s) being built, along with the list of requisite source
>files. The file may be as simple as a single line:

>	obj-m := <module_name>.o

**Comment by diederikdehaas** [comment]
Can you explain what you're trying to do and what you did _exactly_ to try to accomplish it?
Highly preferable with all the exact commands and with the full output.
It's probably also useful to include the output of `uname -a` so I can see against which kernel you're trying to build it.

I always just do `make` and `sudo make install` and everything is fine.

**Comment by KonomiKitten** [comment]
Do you frequent IRC? I'd rather explain it all there if possible?

**Comment by diederikdehaas** [comment]
Yes, I'm `diederik` on both freenode and on oftc

**Pull request closed without merging**
