### PR TITLE
Fix incorrect VHT capabilities, freezes and delays

### PR DESCRIPTION
**Pull request by ghost**
1. Add option `CONFIG_DISABLE_REGD_C`:
   Provides an easy way to disable the code in `os_dep/linux/wifi_regd.c`. When setting up 802.11ac AP (e.g. by using hostapd), `wifi_regd.c` disables many channels in 5GHz regardless of the regulatory domain. This problems seems to affect 802.11ac only since it uses 80MHz/160MHz, and thus using channels that are disabled by the `wifi_regd.c`.
   When CRDA and wireless-regdb are installed, these two programs should be able to help users operate the device in accordance with the law/regulations.
   Affected files: `Makefile`, `os_dep/linux/wifi_regd.c`
2. Fix incorrect VHT capabilities:
   With reference to `core/rtw_vht.c`, `os_dep/linux/ioctl_cfg80211.c` is modified such that the driver can determine and report the VHT capabilities more accurately than the previous version.
   Affected files: `include/rtw_vht.h` (`VHT_MCS_DATA_RATE` is made available for use in `os_dep/linux/ioctl_cfg80211.c`), `os_dep/linux/ioctl_cfg80211.c`
3. Fix some freezes and delays
   This is done by referring to [this commit](https://github.com/abperiasamy/rtl8812AU_8821AU_linux/commit/2e83034d8723442181749f2781fc9fb411380c15).
   Affected files: `core/rtw_cmd.c`, `include/rtw_mlme_ext.h`, `os_dep/linux/rtw_android.c`

### CODE REVIEW

**Comment by diederikdehaas** [comment]
Hi @uminokoe,

First of all, thanks again for the proposed improvements; they are much appreciated.

But why did you bundle these (to me) completely separate changes into 1 PR and especially 1 commit?
I am a big proponent of [atomic commits](https://seesparkbox.com/foundry/atomic_commits_with_git) and this PR/commit doesn't fit that style.

Especially for more extensive changes it's also handy to have an explanation in the commit message, so that someone reading the code/git log doesn't have to be aware of this particular PR to see why things were changed. Most of my commits in this repo (and I try to do it everywhere) have an extended description so that motivations/links/etc are part of the git repo itself.

The text of your 2nd change would be perfect as far as I'm concerned (AFAIC), where the 'title' (maybe a tad more descriptive) can be the first/primary commit message and the rest of the text would be perfect for the extended commit message part.

As for the changes itself, I'll discuss them in order of quality as I see it:
2) If you would submit the 2nd change, (highly) preferable with the commit message as explained above, I'd merge it in a heartbeat :+1: 

3) I'll just assume that it would improve things and as such I'd likely merge them too, but AFAIC it does suffer (a bit) from the [magic number](https://en.wikipedia.org/wiki/Magic_number_%28programming%29#Unnamed_numerical_constants) [problem](https://stackoverflow.com/questions/47882/what-is-a-magic-number-and-why-is-it-bad), also in the sense as they _seem_ rather arbitrary/'random' to me.
I'm not saying you'd have to replace them with constants, but an explanation as to why a value was changed to the new value, in a comment and/or commit message, (and the consequence of the new value) would be preferable.

1) I really like how you have clearly identified the problem :+1: 
But I'm less thrilled about the 'solution' for the following reasons:
- It's a compile type option, so if you'd need it you'd have to change the Makefile and recompile the driver. As I see this driver primarily targeted at people who want to use the AC part of their device, it would make sense to enable it by default. 
- It's not clear to me if it would have any negatively effects outside the identified problem, and what/when that would be, as it would NOT run the `_rtw_regd_init_wiphy` function which I assume does have a reason for being there. If that function does the wrong thing, then fixing that function would seem more logical to me.
- As a consequence of the previous item, it feels like this code change would be done during a debugging session in order to precisely locate the (code) issue and trying to find a solution for it, rather then the actual solution to the problem. Therefor it seems **to me** like a candidate for an issue and not yet of a PR. 

Sorry if I misinterpreted things and please do correct me then.

As the PR is now, I will not merge it. But if you could split it up into 3 PRs (or 2 PRs and an issue) that would surely help/fix my issues with _this_ PR as it is.

**Comment by uminokoe** [comment]
About the `Makefile` and related changes:
The "solution" can be said as temporary because I have yet to figure out what causes the problem. Provided that I have time and adequate knowledge, as well as a good understanding of the code, I shall attempt to fix the problem.

About the VHT capabilities fix:
I shall accept your advice and submit a pull request which is solely related to the issue. However I do wonder whether I can revert the commit - will my _revert commit_ be included in the pull request?
(Imagine a git log like this: )
```
Owner: Merge pull request from Random User
Random User: A good commit
Random User: Revert unwanted commit <- This
Random User: An unwanted commit
```

About the "freezes and delays":
[This commit](https://github.com/joseph-jja/rtl8812AU_8821AU_linux/commit/5b2a0f8609f83db810f3d66ad12d47701df9eecc) only mentions "port some changes from another repo to this one to fix lags", and [this pull request](https://github.com/abperiasamy/rtl8812AU_8821AU_linux/pull/81#issue-100470745) mentions "Seems the driver has a SURVEY_TO delay set to 100 but setting to 0 seems to be fine. Also changing some of the polling seems to fix some freezing.". I am not sure whether the fix helps or the "lag/freezing" exists, so I guess I will not touch it. Please ignore this part.

**Comment by diederikdehaas** [comment]
> However I do wonder whether I can revert the commit - will my revert commit be included in the pull request?

Assuming that is something you don't want, this is one way to go about it:

```
diederik@bagend:~/dev/drivers/rtl8812AU$ git log -3 --oneline 
6d5da20 Fix incorrect VHT capabilities, Fix some freezes and delays
aba2f26 Add support for kernels >= 4.7.
fff6fc4 Merge pull request #14 from uminokoe/4.3.22-beta-add-vht
diederik@bagend:~/dev/drivers/rtl8812AU$ git reset HEAD~1
Unstaged changes after reset:
M       Makefile
M       core/rtw_cmd.c
M       include/rtw_mlme_ext.h
M       include/rtw_vht.h
M       os_dep/linux/ioctl_cfg80211.c
M       os_dep/linux/rtw_android.c
M       os_dep/linux/wifi_regd.c
diederik@bagend:~/dev/drivers/rtl8812AU$ git status
On branch uminokoe-vht-capabilites
Your branch is behind 'uminokoe/driver-4.3.22-beta' by 1 commit, and can be fast-forwarded.
  (use "git pull" to update your local branch)
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

        modified:   Makefile
        modified:   core/rtw_cmd.c
        modified:   include/rtw_mlme_ext.h
        modified:   include/rtw_vht.h
        modified:   os_dep/linux/ioctl_cfg80211.c
        modified:   os_dep/linux/rtw_android.c
        modified:   os_dep/linux/wifi_regd.c

no changes added to commit (use "git add" and/or "git commit -a")
diederik@bagend:~/dev/drivers/rtl8812AU$ git checkout -b fix-incorrect-vht-capabilities
M       Makefile
M       core/rtw_cmd.c
M       include/rtw_mlme_ext.h
M       include/rtw_vht.h
M       os_dep/linux/ioctl_cfg80211.c
M       os_dep/linux/rtw_android.c
M       os_dep/linux/wifi_regd.c
Switched to a new branch 'fix-incorrect-vht-capabilities'
diederik@bagend:~/dev/drivers/rtl8812AU$ git add os_dep/linux/ioctl_cfg80211.c 
diederik@bagend:~/dev/drivers/rtl8812AU$ git add include/rtw_vht.h 
<if you want only part of a file to be added to the commit, use 'git add -i' and stage the hunks you'd like to include in the commit>
diederik@bagend:~/dev/drivers/rtl8812AU$ git status
On branch fix-incorrect-vht-capabilities
Changes to be committed:
  (use "git reset HEAD <file>..." to unstage)

        modified:   include/rtw_vht.h
        modified:   os_dep/linux/ioctl_cfg80211.c

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

        modified:   Makefile
        modified:   core/rtw_cmd.c
        modified:   include/rtw_mlme_ext.h
        modified:   os_dep/linux/rtw_android.c
        modified:   os_dep/linux/wifi_regd.c

diederik@bagend:~/dev/drivers/rtl8812AU$ git diff --cached
diff --git a/include/rtw_vht.h b/include/rtw_vht.h
index def791a..737ed3f 100755
--- a/include/rtw_vht.h
+++ b/include/rtw_vht.h
@@ -138,6 +138,7 @@ void        rtw_process_vht_op_mode_notify(_adapter *padapter, u8 *pframe, PVOID sta);
 u32    rtw_restructure_vht_ie(_adapter *padapter, u8 *in_ie, u8 *out_ie, uint in_len, uint *pout_len);
 void   VHTOnAssocRsp(_adapter *padapter);
 u8     rtw_vht_mcsmap_to_nss(u8 *pvht_mcs_map);
+extern const u16 VHT_MCS_DATA_RATE[3][2][30];

 #endif //_RTW_VHT_H_

diff --git a/os_dep/linux/ioctl_cfg80211.c b/os_dep/linux/ioctl_cfg80211.c
index ca7a221..4ded16f 100755
--- a/os_dep/linux/ioctl_cfg80211.c
+++ b/os_dep/linux/ioctl_cfg80211.c
@@ -6334,90 +6334,109 @@ static void rtw_cfg80211_init_ht_capab(_adapter *padapter, struct ieee80211_sta_

 }

-static void rtw_cfg80211_init_vht_capab_ex(_adapter *padapter, struct ieee80211_sta_vht_cap *vht_cap, u8 rf_type)
+static void rtw_cfg80211_init_vht_capab(_adapter *padapter, struct ieee80211_sta_vht_cap *vht_cap, u8 rf_type)
 {
-//todo: Support for other bandwidths
-
-/* NSS = Number of Spatial Streams */
-#define MAX_BIT_RATE_80MHZ_NSS3                1300    /* Mbps */
-#define MAX_BIT_RATE_80MHZ_NSS2                867             /* Mbps */
-#define MAX_BIT_RATE_80MHZ_NSS1                434             /* Mbps */
-
        struct registry_priv *pregistrypriv = &padapter->registrypriv;
        struct mlme_priv        *pmlmepriv = &padapter->mlmepriv;
        struct vht_priv *pvhtpriv = &pmlmepriv->vhtpriv;
+       u8 bw, rf_num;
+       u16 HighestRate;

+        vht_cap->vht_supported = _TRUE;
        rtw_vht_use_default_setting(padapter);
+       
+        /* Reference: core/rtw_vht.c */
+       /* MCS map */
+       vht_cap->vht_mcs.tx_mcs_map = pvhtpriv->vht_mcs_map[0] | (pvhtpriv->vht_mcs_map[1] << 8);
+       vht_cap->vht_mcs.rx_mcs_map = vht_cap->vht_mcs.tx_mcs_map;

-       /* RX LDPC */
-       if (TEST_FLAG(pvhtpriv->ldpc_cap, LDPC_VHT_ENABLE_RX))
+       /* B0 B1 Maximum MPDU Length */
+       vht_cap->cap |= IEEE80211_VHT_CAP_MAX_MPDU_LENGTH_11454;
+       
+       /* B2 B3 Supported Channel Width Set */
+       if (hal_chk_bw_cap(padapter, BW_CAP_160M) && REGSTY_IS_BW_5G_SUPPORT(pregistrypriv, CHANNEL_WIDTH_160)) {
+               if (hal_chk_bw_cap(padapter, BW_CAP_80_80M) && REGSTY_IS_BW_5G_SUPPORT(pregistrypriv, CHANNEL_WIDTH_80_80))
+                       vht_cap->cap |= IEEE80211_VHT_CAP_SUPP_CHAN_WIDTH_160_80PLUS80MHZ;
+               else
+                       vht_cap->cap |= IEEE80211_VHT_CAP_SUPP_CHAN_WIDTH_160MHZ;
+       }
+       
+       // B4 Rx LDPC
+       if(TEST_FLAG(pvhtpriv->ldpc_cap, LDPC_VHT_ENABLE_RX))
+       {
                vht_cap->cap |= IEEE80211_VHT_CAP_RXLDPC;
+       }

-       /* TX STBC */
-       if (TEST_FLAG(pvhtpriv->stbc_cap, STBC_VHT_ENABLE_TX))
-               vht_cap->cap |= IEEE80211_VHT_CAP_TXSTBC;
+       // B5 ShortGI for 80MHz
+       vht_cap->cap |= IEEE80211_VHT_CAP_SHORT_GI_80;

-       /* RX STBC */
-       if (TEST_FLAG(pvhtpriv->stbc_cap, STBC_VHT_ENABLE_RX)) {
-               switch (rf_type) {
-               case RF_1T1R:
-                       vht_cap->cap |= IEEE80211_VHT_CAP_RXSTBC_1;/*RX STBC One spatial stream*/
-                       break;
-               case RF_2T2R:
-               case RF_1T2R:
-                       vht_cap->cap |= IEEE80211_VHT_CAP_RXSTBC_2;/*RX STBC Two spatial streams*/
-                       break;
-               case RF_3T3R:
-               case RF_3T4R:
-               case RF_4T4R:
-                       vht_cap->cap |= IEEE80211_VHT_CAP_RXSTBC_3;/*RX STBC Three spatial streams*/
-                       break;
-               default:
-                       DBG_871X("[warning] rf_type %d is not expected\n", rf_type);
-                       break;
-               }
+       // B6 ShortGI for 160MHz
+       // todo
+
+       // B7 Tx STBC
+       if(TEST_FLAG(pvhtpriv->stbc_cap, STBC_VHT_ENABLE_TX))
+       {
+               vht_cap->cap |= IEEE80211_VHT_CAP_TXSTBC;
+       }
+       
+       // B8 B9 B10 Rx STBC
+       if(TEST_FLAG(pvhtpriv->stbc_cap, STBC_VHT_ENABLE_RX))
+       {
+               rtw_hal_get_hwreg(padapter, HW_VAR_RF_TYPE, (u8 *)(&rf_type));
+               if ((rf_type == RF_2T2R) || (rf_type == RF_1T2R)) 
+                       vht_cap->cap |= IEEE80211_VHT_CAP_RXSTBC_1;
+               else if (rf_type == RF_1T1R) 
+                       vht_cap->cap |= IEEE80211_VHT_CAP_RXSTBC_1;
+       }       
+       
+       // B11 SU Beamformer Capable
+       if (TEST_FLAG(pvhtpriv->beamform_cap, BEAMFORMING_VHT_BEAMFORMER_ENABLE)) {             
+               vht_cap->cap |= IEEE80211_VHT_CAP_SU_BEAMFORMER_CAPABLE;
+               // B16 17 18 Number of Sounding Dimensions
+               rtw_hal_get_def_var(padapter, HAL_DEF_BEAMFORMER_CAP, (u8 *)&rf_num);
+               vht_cap->cap |= rf_num << IEEE80211_VHT_CAP_SOUNDING_DIMENSIONS_SHIFT;
        }

-       /* switch (rf_type) {
-       case RF_1T1R:
-               vht_cap->vht_mcs.tx_highest = MAX_BIT_RATE_80MHZ_NSS1;
-               vht_cap->vht_mcs.rx_highest = MAX_BIT_RATE_80MHZ_NSS1;
-               break;
-       case RF_2T2R:
-       case RF_1T2R:
-               vht_cap->vht_mcs.tx_highest = MAX_BIT_RATE_80MHZ_NSS2;
-               vht_cap->vht_mcs.rx_highest = MAX_BIT_RATE_80MHZ_NSS2;
-               break;
-       case RF_3T3R:
-       case RF_3T4R:
-       case RF_4T4R:
-               vht_cap->vht_mcs.tx_highest = MAX_BIT_RATE_80MHZ_NSS3;
-               vht_cap->vht_mcs.rx_highest = MAX_BIT_RATE_80MHZ_NSS3;
-               break;
-       default:
-               DBG_871X("[warning] rf_type %d is not expected\n", rf_type);
-               break;
-       } */
+       // B12 SU Beamformee Capable
+       if (TEST_FLAG(pvhtpriv->beamform_cap, BEAMFORMING_VHT_BEAMFORMEE_ENABLE)) {
+               vht_cap->cap |= IEEE80211_VHT_CAP_SU_BEAMFORMEE_CAPABLE;
+               // B13 14 15 Compressed Steering Number of Beamformer Antennas Supported
+               rtw_hal_get_def_var(padapter, HAL_DEF_BEAMFORMEE_CAP, (u8 *)&rf_num);
+               vht_cap->cap |= rf_num << IEEE80211_VHT_CAP_BEAMFORMEE_STS_SHIFT;
+       }

-       /* MCS map */
-       vht_cap->vht_mcs.tx_mcs_map = pvhtpriv->vht_mcs_map[0] | (pvhtpriv->vht_mcs_map[1] << 8);
-       vht_cap->vht_mcs.rx_mcs_map = vht_cap->vht_mcs.tx_mcs_map;
+       //HW don't support mu bfee/bfer
+       // B19 MU Beamformer Capable
+       // B20 MU Beamformee Capable
+       
+       //TXOP PS disabled or not supported
+       // B21 VHT TXOP PS
+       
+       // B22 +HTC-VHT Capable
+       vht_cap->cap |= IEEE80211_VHT_CAP_HTC_VHT;

-       if (rf_type == RF_1T1R) {
-               vht_cap->vht_mcs.tx_highest = MAX_BIT_RATE_80MHZ_NSS1;
-               vht_cap->vht_mcs.rx_highest = MAX_BIT_RATE_80MHZ_NSS1;
+       // B23 24 25 Maximum A-MPDU Length Exponent
+       if (pregistrypriv->ampdu_factor != 0xFE)
+       {
+               vht_cap->cap |= pregistrypriv->ampdu_factor << IEEE80211_VHT_CAP_MAX_A_MPDU_LENGTH_EXPONENT_SHIFT;
        }
+       else
+       {
+               vht_cap->cap |= 7 << IEEE80211_VHT_CAP_MAX_A_MPDU_LENGTH_EXPONENT_SHIFT;
+       }
+       
+       // Link Adaptation not supported
+       // B26 27 VHT Link Adaptation Capable

-       if (pvhtpriv->sgi_80m)
-               vht_cap->cap |= IEEE80211_VHT_CAP_SHORT_GI_80;
-
-       vht_cap->cap |= (pvhtpriv->ampdu_len << IEEE80211_VHT_CAP_MAX_A_MPDU_LENGTH_EXPONENT_SHIFT);
-}
+       /* find the largest bw supported by both registry and hal */
+       bw = hal_largest_bw(padapter, REGSTY_BW_5G(pregistrypriv));

-static void rtw_cfg80211_init_vht_capab(_adapter *padapter, struct ieee80211_sta_vht_cap *vht_cap, u8 rf_type)
-{
-       vht_cap->vht_supported = _TRUE;
-       rtw_cfg80211_init_vht_capab_ex(padapter, vht_cap, rf_type);
+       HighestRate = VHT_MCS_DATA_RATE[bw][pvhtpriv->sgi_80m][((pvhtpriv->vht_highest_rate - MGN_VHT1SS_MCS0)&0x3f)];
+       HighestRate = (HighestRate+1) >> 1;
+       
+       
+       vht_cap->vht_mcs.tx_highest = HighestRate; //indicate we support highest rx rate is 600Mbps.
+       vht_cap->vht_mcs.rx_highest = HighestRate; //indicate we support highest rx rate is 600Mbps.    
 }

 void rtw_cfg80211_init_wiphy(_adapter *padapter)

<verify that these are indeed all the changes that need to be part of the commit>
diederik@bagend:~/dev/drivers/rtl8812AU$ git commit -v
[fix-incorrect-vht-capabilities d41717a] Fix incorrect VHT capabilities.
 2 files changed, 87 insertions(+), 67 deletions(-)
diederik@bagend:~/dev/drivers/rtl8812AU$ git log -2
commit d41717a5828b51870800a8bdf8b8068a0a04946c
Author: Diederik de Haas <github@cknow.org>
Date:   Thu Sep 22 15:26:47 2016 +0200

    Fix incorrect VHT capabilities.

    With reference to core/rtw_vht.h, os_dep/linux/ioctl_cfg80211.c is
    modified such that the driver can determine and report the VHT
    capabilities more accurately than the previous version.
diederik@bagend:~/dev/drivers/rtl8812AU$
```

Now you can push this branch to your repo and then you can submit your new PR from that.

Right now you still have uncommitted changes in your `fix-incorrect-vht-capabilities` (local) branch, which should be moved to (another) new branch and you can do that with

```
git checkout -b <new-branch-name>
git add [-i] <file1>     # add file or part of file to staging area for new commit
git add [-i] <file2>     # add file or part of file to staging area for new commit
...
git add [-i] <fileN>     # add file or part of file to staging area for new commit
git commit -v            # open your preferred file editor to create your commit message
git push                    # this will actually give an error, but git will tell you what to do
```

and repeat that until all changes are done.

But then you'd still have the one/big commit from this PR in your `driver-4.3.22-beta` and you can completely undo that with:

```
git checkout driver-4.3.22-beta
git reset --hard HEAD~1
git push --force
```

Assuming you see this repo as _just_ your fork to submit changes, you can do this (technically you always can).

But as soon as others start to use your (public) repo, you should _own up_ to your mistake and actually do the `git revert` which will show up in your git history. You are rewriting history and would/can break other people's clone with it. 
That's why you need to use the `--force` parameter to tell git you _really_ want to do this.

This repo is actually an example of me starting out wrong and fixing it later on and therefor it does have a _Revert XXX_ in its history to undo that false start.
But it's actually not a big deal as all people make mistakes. Git just makes it really easy to undo that and do it again.
As a matter of fact, that's one of the primary reasons I like atomic commits so much :wink: 

HTH

**Comment by diederikdehaas** [comment]
Just noticed https://github.com/diederikdehaas/rtl8812AU/pull/18 which has some more comments regarding the `Makefile` and `CONFIG_DISABLE_REGD_C`
Apologies for the horrible backlog :-/

**Pull request closed without merging**
